# Generated by Django 5.1.2 on 2024-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('tecnico', 'Tecnico'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
